"""rename department

Revision ID: 72418ac227ba
Revises: 933dc95dacd9
Create Date: 2024-06-26 11:32:45.914644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72418ac227ba'
down_revision = '933dc95dacd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
